name: build

on:
  push:
    branches:
      - "master"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Package
      run: |
        ls /Applications/
        xcode-select -p
        xcode-select --switch /Applications/Xcode_11.app/
        swift package generate-xcodeproj
        xcodebuild clean build -project $PROJECT -scheme $SCHEME -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env:
        PROJECT: FocusEntity.xcodeproj
        SCHEME: FocusEntity-Package
        DESTINATION: platform=iOS Simulator,name=iPhone Xs
